# Generated by Django 4.2.4 on 2023-08-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero_comision', models.IntegerField()),
                ('mail', models.EmailField(default='example@example.com', max_length=40)),
            ],
        ),
    ]
