# Generated by Django 4.2.4 on 2023-08-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mas', models.CharField(default='name', max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('raza', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('dueño', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vet', models.CharField(max_length=40)),
                ('apellido_vet', models.CharField(max_length=40)),
                ('telefono_vet', models.IntegerField()),
                ('legajo', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_comision',
            new_name='telefono_cli',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_cli',
            field=models.CharField(default='lastname', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_cli',
            field=models.CharField(default='name', max_length=40),
        ),
    ]
