# Generated by Django 4.2.4 on 2023-08-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_animal_veterinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre_mas',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_cli',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cli',
            field=models.CharField(max_length=40),
        ),
    ]
