# Generated by Django 4.2.4 on 2023-08-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_animal_nombre_mas_alter_cliente_apellido_cli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(max_length=50),
        ),
    ]
